# Generated by Django 5.1.6 on 2025-02-23 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
                ('script', models.CharField(blank=True, max_length=100)),
                ('native_info', models.TextField(blank=True)),
                ('translation_info', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.BigIntegerField(blank=True, null=True)),
                ('state', models.CharField(default='Learning', max_length=20)),
                ('step', models.IntegerField(blank=True, null=True)),
                ('stability', models.FloatField(blank=True, null=True)),
                ('difficulty', models.FloatField(blank=True, null=True)),
                ('due', models.DateTimeField(blank=True, null=True)),
                ('last_review', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_practices', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_practices', to='main.word')),
            ],
            options={
                'unique_together': {('user', 'word')},
            },
        ),
    ]
