# Generated by Django 5.1.6 on 2025-03-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_prompt_answer_prompt_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
