# Generated by Django 5.1.6 on 2025-03-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_prompt_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='message',
            new_name='content',
        ),
        migrations.AddField(
            model_name='prompt',
            name='is_active_prompt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prompt',
            name='task',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
